//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElemenTable.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElemenTable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actinoid.
        /// </summary>
        internal static string Actinoid {
            get {
                return ResourceManager.GetString("Actinoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alkali metal.
        /// </summary>
        internal static string AlkaliMetal {
            get {
                return ResourceManager.GetString("AlkaliMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alkaline earth metal.
        /// </summary>
        internal static string AlkalineEarthMetal {
            get {
                return ResourceManager.GetString("AlkalineEarthMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas.
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Halogen.
        /// </summary>
        internal static string Halogen {
            get {
                return ResourceManager.GetString("Halogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lanthanoid.
        /// </summary>
        internal static string Lanthanoid {
            get {
                return ResourceManager.GetString("Lanthanoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liquid.
        /// </summary>
        internal static string Liquid {
            get {
                return ResourceManager.GetString("Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metalloid.
        /// </summary>
        internal static string Metalloid {
            get {
                return ResourceManager.GetString("Metalloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noble gas.
        /// </summary>
        internal static string NobleGas {
            get {
                return ResourceManager.GetString("NobleGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nonmetal.
        /// </summary>
        internal static string Nonmetal {
            get {
                return ResourceManager.GetString("Nonmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post-transition metal.
        /// </summary>
        internal static string PostTransitionMetal {
            get {
                return ResourceManager.GetString("PostTransitionMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radioactive.
        /// </summary>
        internal static string Radioactive {
            get {
                return ResourceManager.GetString("Radioactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radioactivity {
            get {
                object obj = ResourceManager.GetObject("radioactivity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solid.
        /// </summary>
        internal static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stable.
        /// </summary>
        internal static string Stable {
            get {
                return ResourceManager.GetString("Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synthetic.
        /// </summary>
        internal static string Synthetic {
            get {
                return ResourceManager.GetString("Synthetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodic Table.
        /// </summary>
        internal static string title_print {
            get {
                return ResourceManager.GetString("title_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transition metal.
        /// </summary>
        internal static string TransitionMetal {
            get {
                return ResourceManager.GetString("TransitionMetal", resourceCulture);
            }
        }
    }
}
